Filterlast updated date hire
HackYourFuture-CPH/hackyourfuture.dk pull request #124
Opened 2020-09-09 16:46 UTC by sowmya1408

Hi 

I have added the functionality to filter profiles which have not been updated from 6months and also checked changing the dates in alumni.json and it works fine.

I have also changed a duplicate id in alumni.json.

2020-09-22 11:22 UTC, benna100 requested changes
Does the filter not dissapear when people start filtering for specific things? 

I'm fairly certain it will. Fx line 41 that uses the original alumniList so there the filter of last update will not be in affect

2020-09-23 18:18 UTC, sowmya1408 commented
Yes Benjamin 👍 , I did not check before, but I could see it now that the skills filter disappears and also the hire profile. I have now applied the changes of uniqueskills on to the original alumni array and it works fine now.

Please let me know if I still need to make any more changes.

Thank you :)

2020-10-01 08:43 UTC, benna100 reviewed
I'm fairly sure this does not work. Have you tested this?

2020-10-01 08:43 UTC, benna100 commented on components/hire/alumni.json
> +    "id": 33,
Why are you changing this id?

2020-10-01 09:31 UTC, sowmya1408 commented on components/hire/alumni.json
> +    "id": 33,
Hi Benjamin,
I have tested it and is working completely fine.
I have changed the id's because there were two duplicate id's and there was an error in the console.

2020-10-06 11:45 UTC, benna100 commented on components/hire/alumni.json
> +    "id": 33,
I just tested it and it does not work.

Are you sure you understand what the problem is?

2020-10-07 12:39 UTC, sowmya1408 commented on components/hire/alumni.json
> +    "id": 33,
Hi Benjamin,

Thinks I see working are:
1. In hire page it does not show the profiles which are not updated from last 6 months.
2. But, when we search with filters, we are able to see the profile(which is not updated from last 6months) which matches the search.

2020-10-20 11:12 UTC, benna100 commented on components/hire/alumni.json
> +    "id": 33,
When you click on a skill. The filter gets removed. That is not supposed to happen. The filter should always be active. It should not be possible to see people that have not updated their info in 6 months!

2020-11-05 19:36 UTC, sowmya1408 commented on components/hire/alumni.json
> +    "id": 33,
Hi Benjamin,
I have added the filter to newAlumniList as well, now it will not show the profiles which are not updated from last 6 months.
I hope I have solved the problem this time :)

2020-11-11 09:46 UTC, benna100 requested changes

2020-11-11 09:46 UTC, benna100 commented on components/hire/Hire.js
> +      )
When you have duplicate code like this. Then we need to put this functionality into a function. 

Never write the same functionality twice, it **always** ends up giving problems

But it works, so good job on that :D

2020-12-15 15:51 UTC, sowmya1408 commented on components/hire/Hire.js
> +      )
I have tried to put this in to a function, but there is a problem as the filter should apply on initial state, so when I do that it crashes the whole page.

It would really help me if you have any suggestion to not repeat the code twice in this case :)

2021-01-07 09:48 UTC, benna100 commented on components/hire/Hire.js
> +      )
You need to figure out why it is crashing then. What error is it throwing?

2021-02-20 19:20 UTC, dpfernandes commented
@sowmya1408 Can we close this PR?

2021-02-21 14:37 UTC, dpfernandes commented
Issue solved on #151

2021-02-21 14:37 UTC, closed without merging