Cypress tests for the apply form
HackYourFuture-CPH/hackyourfuture.dk pull request #131
Opened 2020-10-09 09:09 UTC by cecastosic

2020-10-20 11:38 UTC, benna100 requested changes
Please make the PR to develop not master.

Why is the why.docs file empty?

Please add a readme.md with documentation :)

2020-10-20 11:39 UTC, benna100 commented
But **really** good work Svetlana! Thank you so much for this!!

2020-10-24 22:12 UTC, cecastosic commented on cypress/plugins/index.js
> +}
Once we decide to write plugins (custom code that executes during particular stages of the Cypress lifecycle) the code should be written here. The both, folder and file come with cypress installation.

2020-10-24 22:15 UTC, cecastosic commented on cypress/support/index.js
> +// require('./commands')
By default Cypress will automatically include the support file cypress/support/index.js. This file runs before every single spec file. We do this purely as a convenience mechanism so you don’t have to import this file in every single one of your spec files. https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Support-file

2020-10-24 22:15 UTC, cecastosic commented on cypress/support/commands.js
> +import 'cypress-file-upload'
https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-files

2020-10-24 22:52 UTC, cecastosic commented
> Please make the PR to develop not master.
> 
> Why is the why.docs file empty?
> 
> Please add a readme.md with documentation :)

Done
why.doc is not empty 
<img width="512" alt="Screenshot 2020-10-25 at 00 07 15" src="https://user-images.githubusercontent.com/10253713/97095151-3fe97980-165c-11eb-959f-ad4cd2bdaa88.png">

2020-10-25 12:56 UTC, benna100 commented on cypress/plugins/index.js
> +}
Okay, cool!

2020-10-25 12:56 UTC, benna100 commented on cypress/support/commands.js
> +import 'cypress-file-upload'
Okay, fair :)

2020-10-25 12:57 UTC, benna100 commented on cypress/support/index.js
> +// require('./commands')
Okay, cool!

2020-10-25 13:00 UTC, benna100 requested changes
The documentation that you have in the why.docs what is that?

Documentation for cypress should be written in a readme.md file. Maybe you can add a testing section to this readme: https://github.com/HackYourFuture-CPH/hackyourfuture.dk/blob/master/README.md

2020-10-25 14:59 UTC, cecastosic commented
> The documentation that you have in the why.docs what is that?
> 
> Documentation for cypress should be written in a readme.md file. Maybe you can add a testing section to this readme: https://github.com/HackYourFuture-CPH/hackyourfuture.dk/blob/master/README.md

I just put questions from the form in the why.doc file to not be empty.
Regarding readme, I added readme here https://github.com/cecastosic/hackyourfuture.dk/blob/test/cypress/README.md

2020-10-26 09:04 UTC, benna100 commented
Ahh perfect, thanks :)

2020-10-26 09:05 UTC, benna100 approved these changes

2020-10-26 09:05 UTC, merged