Deepti HireProfile as of 20Feb2021
HackYourFuture-CPH/hackyourfuture.dk pull request #156
Opened 2021-02-20 21:26 UTC by Deepti-Dk

2021-02-20 21:34 UTC, AnilMula approved these changes

2021-02-20 21:34 UTC, AnilMula approved these changes

2021-02-20 21:40 UTC, AnilMula approved these changes

2021-02-20 21:58 UTC, dpfernandes requested changes
Your profile doesn't need to chance deadline.js or other stuff. Please review your commits.

2021-02-21 08:40 UTC, Deepti-Dk commented
Will create a new PR.

2021-02-21 08:41 UTC, closed without merging